/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author HP
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMenu1 = new javax.swing.JButton();
        btMenu2 = new javax.swing.JButton();
        btMenu3 = new javax.swing.JButton();
        btMenu4 = new javax.swing.JButton();
        btMenu6 = new javax.swing.JButton();
        btMenu5 = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btMenu7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 25, 88));

        btMenu1.setBackground(new java.awt.Color(51, 51, 255));
        btMenu1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu1.setForeground(new java.awt.Color(240, 240, 240));
        btMenu1.setText("Empleados");
        btMenu1.setBorder(null);
        btMenu1.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu1.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu1.setPreferredSize(new java.awt.Dimension(120, 100));

        btMenu2.setBackground(new java.awt.Color(51, 51, 255));
        btMenu2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu2.setForeground(new java.awt.Color(240, 240, 240));
        btMenu2.setText("Productos");
        btMenu2.setBorder(null);
        btMenu2.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu2.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu2.setPreferredSize(new java.awt.Dimension(120, 100));

        btMenu3.setBackground(new java.awt.Color(51, 51, 255));
        btMenu3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btMenu3.setText("Proveedores");
        btMenu3.setBorder(null);
        btMenu3.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu3.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu3.setPreferredSize(new java.awt.Dimension(120, 100));

        btMenu4.setBackground(new java.awt.Color(51, 51, 255));
        btMenu4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btMenu4.setText("Mobiliario");
        btMenu4.setBorder(null);
        btMenu4.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu4.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu4.setPreferredSize(new java.awt.Dimension(120, 100));

        btMenu6.setBackground(new java.awt.Color(51, 51, 255));
        btMenu6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu6.setForeground(new java.awt.Color(240, 240, 240));
        btMenu6.setText("Registro de ventas");
        btMenu6.setBorder(null);
        btMenu6.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu6.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu6.setPreferredSize(new java.awt.Dimension(120, 100));

        btMenu5.setBackground(new java.awt.Color(51, 51, 255));
        btMenu5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btMenu5.setText("Nueva Venta");
        btMenu5.setBorder(null);
        btMenu5.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu5.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu5.setPreferredSize(new java.awt.Dimension(120, 100));

        btSalir.setBackground(new java.awt.Color(51, 51, 255));
        btSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btSalir.setForeground(new java.awt.Color(240, 240, 240));
        btSalir.setText("Salir");
        btSalir.setBorder(null);
        btSalir.setPreferredSize(new java.awt.Dimension(114, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/03.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("MENU DE OPERACIONES");

        btMenu7.setBackground(new java.awt.Color(51, 51, 255));
        btMenu7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btMenu7.setForeground(new java.awt.Color(240, 240, 240));
        btMenu7.setText("Historial de procesos");
        btMenu7.setBorder(null);
        btMenu7.setMaximumSize(new java.awt.Dimension(120, 100));
        btMenu7.setMinimumSize(new java.awt.Dimension(120, 100));
        btMenu7.setPreferredSize(new java.awt.Dimension(120, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
btMenu2param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeebtMenu2fo : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btMenu1;
    public javax.swing.JButton btMenu2;
    public javax.swing.JButton btMenu3;
    public javax.swing.JButton btMenu4;
    public javax.swing.JButton btMenu5;
    public javax.swing.JButton btMenu6;
    public javax.swing.JButton btMenu7;
    public javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
